### ISSUE TITLE
How to use Dialog.ElicitSlot for Python as Runtime environment

### ISSUE THREAD

**Issue by Nikhil-Wagh** [alexa/skill-sample-python-trivia#4]
I want to fill a slot not at the beginning of the invocation of the intent. I want to provide user some options, and I want them to select one out of those. For that I'm trying to use `Dialog.ElicitSlot`, but somehow I'm getting an error : 

> "Request to skill endpoint resulted in an error."

I'm returning this when I need the user to select an option from my list.
```
return {
	"version": "1.0",
	"sessionAttributes": {},
	"response": {
	"outputSpeech": {
		"type": "PlainText",
		"text": "These are the multiplex" + ("es" if len(multi_list) > 1 else "") + " " + outputSpeech + ". Please select one out of these."
		# outputSpeech contains the list of options I want the user to select from
	},
	"shouldEndSession": False,
	"directives": [
		{
			"type": "Dialog.ElicitSlot",
			"slotToElicit": "MULTIPLEX",
			"updatedIntent": {
				"name": "GetMovieDetails",
				"confirmationStatus": "NONE",
				"slots": {
					"CITY" : {
						"name" : "CITY",
						"confirmationStatus" : "NONE",
						"value" : city # this is already filled, it is just anti-capitalised 
					},
					"NAME" : {
						"name" : "NAME",
						"confirmationStatus" : "NONE",
						"value" : movie_name # this is already filled, it is just anti-capitalised 
					},
					"MULTIPLEX" : {
						"name" : "MULTIPLEX",
						"confirmationStatus" : "NONE",
					}
				}
			}
		}
	]
}
```
I'm testing my skill using `python-lambda-local`, it is working fine on my local machine (I just had to change the `dialogState` to `"COMPLETED"` manually, like the one [here](https://github.com/Nikhil-Wagh/Alexa-Flick/blob/f09014b9886a0d40906a8085f5ee3c1eb1554dd3/events/GetMovieDetails02.json#L76)). It returns everything written above. But It gives an error while testing it on Skill Tester. [Here](https://github.com/Nikhil-Wagh/Alexa-Flick/blob/master/events/errorOutput.json) is the output which is returned in the Skill Tester.
PS : I did not check the Slot Filling check box in the Build Section. (As I need the slot to be filled later)

**Comment by danielhhoskins** [comment]
For those who are now looking for an answer to this, I'd guess that increasing the Lambda function timeout was the answer to the problem (it solved the problem for me).

**Comment by ErickAgrazal** [comment]
Hey @danielhhoskins I'm using .ask to deploy this. How can I change it?

**Comment by Nikhil-Wagh** [comment]
@ErickAgrazal  You can change the `timeout` in your aws console. Scroll down below your code.
